### ISSUE TITLE
Question for "USB Hub support to your STM32F4" - By Peter

### ISSUE THREAD

**Issue by PetertheFive** [mori-br/STM32F4HUB#1]
I have tested your stm32 project. It can single HID device, but can not detect the HID under-connect with HUB. 

 
The test COM output is as followed.Can you support me some suggestion for this usage?
![image](https://user-images.githubusercontent.com/39544367/62187434-f39d8400-b39b-11e9-915e-4d0170f7a6d1.png)

**Comment by mori-br** [comment]
I notice that you are trying to connect a low speed device, There´s a problem with this the packet PRE packet is not be sent from STM32 (to indicate that it is a LS device talking) and I don't know why. If you use only FS device it will work.
